// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using MyBlazorApp.Models;
using RestSharp;
using RestSharp.Serializers.NewtonsoftJson;

namespace MyBlazorApp.Components.Pages
{
    public partial class LoginForm(IJSRuntime JS)
    {
        LoginFormModel LoginFormModel = new LoginFormModel();

        [Inject]
        private NavigationManager NavigationManager { get; set; } = default!;

        async Task HandleSubmit()
        {
            const string apiUrl = "https://localhost:7049";
            try
            {
                var client = new RestClient(apiUrl, configureSerialization: ex => ex.UseNewtonsoftJson());
                var req = new RestRequest("/Auth/login", Method.Post).AddJsonBody(LoginFormModel);
                var res = await client.ExecuteAsync<LoginResponse>(req);

                if (res.IsSuccessful && res.Data is not null)
                {
                    var token = res.Data.Token;
                    await JS.InvokeVoidAsync("localStorage.setItem", "authToken", token);
                    NavigationManager.NavigateTo("/home", false);
                }
                else
                {
                    Console.WriteLine($"Login failed. Status: {res.StatusCode}, Content: {res.Content}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error during login: {ex.Message}");
            }

        }
    }
}