// <auto-generated/>
/*
PSEUDOCODE / PLAN:
1. Ensure this Blazor component has an instance of NavigationManager injected so instance methods (NavigateTo) can be called.
2. Add an [Inject] property:
   - Property type: NavigationManager
   - Accessibility: private
   - Name: NavigationManager
   - Provide a non-null default to satisfy the compiler (default!)
3. Preserve existing fields, methods and logic exactly as in the original file.
4. Call the instance property NavigationManager.NavigateTo(...) from HandleSubmit (no changes needed to the call once injection is present).
5. Do not modify any other unrelated code.

This file will therefore:
- keep existing usings and class structure
- add an injected NavigationManager property to fix CS0120
*/

using Microsoft.AspNetCore.Components;
using MyBlazorApp.Models;
using RestSharp;
using RestSharp.Serializers.NewtonsoftJson;

namespace MyBlazorApp.Components.Pages
{
    public partial class Register
    {
        // Inject NavigationManager instance so NavigateTo can be called on the instance (fixes CS0120)
        [Inject]
        private NavigationManager NavigationManager { get; set; } = default!;

        RegisterFormModel RegisterFormModel = new RegisterFormModel();
        async Task HandleSubmit()
        {
            Dictionary<string, string> RequestAdapter = new();

            RequestAdapter.Add("Name", RegisterFormModel.Name);
            RequestAdapter.Add("Email", RegisterFormModel.Email);
            RequestAdapter.Add("Password", RegisterFormModel.Password);

            const string apiUrl = "https://localhost:7049";
            var client = new RestClient(apiUrl, configureSerialization: ex => ex.UseNewtonsoftJson());
            var req = new RestRequest("/User/register", Method.Post).AddJsonBody(RequestAdapter);
            var res = await client.ExecuteAsync<LoginResponse>(req);

            if (res.IsSuccessful)
            {
                var responseData = res.Data;

                //Navigate to the login page after successful registration
                NavigationManager.NavigateTo("/login", false);
            }
            else
            {
                // Handle registration failure, e.g., show error message
            }
        }
    }
}