// <auto-generated/>
using Microsoft.AspNetCore.Components;

namespace MyBlazorApp.Components.Pages
{
    public partial class TaskCard
    {
        [Parameter]
        public int TaskId { get; set; }
        [Parameter]
        public string Title { get; set; } = string.Empty;
        [Parameter]
        public string Description { get; set; }
        [Parameter]
        public string UserName { get; set; } = string.Empty;
        [Parameter]
        public string IssuerName { get; set; } = string.Empty;
        [Parameter]
        public int Status { get; set; }
        [Parameter]
        public DateTime? CreatedAt { get; set; }
        [Parameter]
        public DateTime? StartDate { get; set; }
        [Parameter]
        public DateTime? DueDate { get; set; }

    }
}